import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const ThemeContext = createContext();

export const THEMES = {
  dark: {
    bg: '#0D0D12', cardBg: '#18181F', cardBg2: '#1E1E27',
    border: '#232330', textMain: '#F2F2F7', textSub: '#7B7B8E',
    orange: '#FF6B35', iconBox: '#1E1E2A', iconBorder: '#2A2A3A',
    bottomNav: '#18181F', bottomBorder: '#1F1F2A', statusBar: 'light-content',
  },
  light: {
    bg: '#F4F4F8', cardBg: '#FFFFFF', cardBg2: '#F0F0F5',
    border: '#E0E0EA', textMain: '#1A1A2E', textSub: '#7B7B8E',
    orange: '#FF6B35', iconBox: '#F0F0F5', iconBorder: '#E0E0EA',
    bottomNav: '#FFFFFF', bottomBorder: '#E5E5EA', statusBar: 'dark-content',
  },
};

// ── All Translations ──────────────────────────────────────────────
const TRANSLATIONS = {
  en: {
    appName: 'AI Writer', askAnything: 'Ask me anything…', selectTool: 'Select Tool',
    home: 'Home', history: 'History', settings: 'Settings',
    essayWriter: 'Essay Writer', essayDesc: 'Generate high-quality essays.',
    storyWriter: 'Story Writer', storyDesc: 'Create imaginative stories.',
    poemWriter: 'Poem Writer', poemDesc: 'Words into beautiful poems.',
    emailWriter: 'Email Writer', emailDesc: 'Write personalized emails.',
    paragraphWriter: 'Paragraph Writer', paragraphDesc: 'Clear paragraphs for any topic.',
    enterTopic: 'Enter Topic', topicPlaceholder: 'i.e The power of gratitude...',
    sampleText: 'Sample text', essayType: 'Essay Type', academicLevel: 'Academic Level',
    generateEssay: 'Generate Essay', generating: 'Generating...', generatedEssay: 'Generated Essay',
    short: 'Short', medium: 'Medium', long: 'Long', pleaseEnterTopic: 'Please enter topic',
    setCreativity: 'Set Creativity', selectGenre: 'Select Genre', selectStyles: 'Select Styles',
    generateStory: 'Generate Story', generatingStory: 'Generating Story...', generatedStory: 'Generated Story',
    topicRequired: 'Topic required', enterTopicFirst: 'Please enter a topic first.',
    poemType: 'Poem Type', generatePoem: 'Generate Poem', generatingPoem: 'Generating Poem...', generatedPoem: 'Generated Poem',
    writeEmail: 'Write Email', replyEmail: 'Reply Email', emailTopic: 'Email topic', replyTopic: 'Reply topic',
    generateEmail: 'Generate Email', generateReply: 'Generate Reply',
    generatingEmail: 'Generating Email...', generatingReply: 'Generating Reply...',
    generatedEmail: 'Generated Email', generatedReply: 'Generated Reply',
    topicRequiredMsg: 'Please enter an email topic first.',
    noHistoryYet: 'No History Yet', noHistorySubtitle: "Generate essays, poems or stories\nand they'll appear here.",
    startWriting: 'Start Writing', clearAll: 'Clear All',
    deleteHistory: 'Remove this item from history?', deleteAllHistory: 'Delete all history?',
    delete: 'Delete', cancel: 'Cancel', all: 'All',
    settingsTitle: 'Settings', account: 'Account', subscription: 'Subscription',
    theme: 'Theme', languages: 'Languages', reportContent: 'Report Content',
    rateUs: 'Rate us', contactUs: 'Contact Us', about: 'About',
    privacyPolicy: 'Privacy Policy', termsConditions: 'Terms & Conditions',
    featureRequest: 'Feature Request', logout: 'Logout', close: 'Close',
    writingTone: 'Writing Tone', length: 'Length', generateParagraphs: 'Generate Paragraphs',
  },
  hi: {
    appName: 'AI राइटर', askAnything: 'कुछ भी पूछें…', selectTool: 'टूल चुनें',
    home: 'होम', history: 'इतिहास', settings: 'सेटिंग्स',
    essayWriter: 'निबंध लेखक', essayDesc: 'उच्च गुणवत्ता के निबंध बनाएं।',
    storyWriter: 'कहानी लेखक', storyDesc: 'रचनात्मक कहानियां बनाएं।',
    poemWriter: 'कविता लेखक', poemDesc: 'शब्दों को सुंदर कविता में बदलें।',
    emailWriter: 'ईमेल लेखक', emailDesc: 'व्यक्तिगत ईमेल लिखें।',
    paragraphWriter: 'पैराग्राफ लेखक', paragraphDesc: 'किसी भी विषय पर स्पष्ट पैराग्राफ।',
    enterTopic: 'विषय दर्ज करें', topicPlaceholder: 'जैसे कृतज्ञता की शक्ति...',
    sampleText: 'नमूना पाठ', essayType: 'निबंध प्रकार', academicLevel: 'शैक्षणिक स्तर',
    generateEssay: 'निबंध बनाएं', generating: 'बन रहा है...', generatedEssay: 'बना हुआ निबंध',
    short: 'छोटा', medium: 'मध्यम', long: 'लंबा', pleaseEnterTopic: 'कृपया विषय दर्ज करें',
    setCreativity: 'रचनात्मकता चुनें', selectGenre: 'शैली चुनें', selectStyles: 'स्टाइल चुनें',
    generateStory: 'कहानी बनाएं', generatingStory: 'कहानी बन रही है...', generatedStory: 'बनी हुई कहानी',
    topicRequired: 'विषय आवश्यक', enterTopicFirst: 'कृपया पहले विषय दर्ज करें।',
    poemType: 'कविता प्रकार', generatePoem: 'कविता बनाएं', generatingPoem: 'कविता बन रही है...', generatedPoem: 'बनी हुई कविता',
    writeEmail: 'ईमेल लिखें', replyEmail: 'ईमेल का जवाब', emailTopic: 'ईमेल विषय', replyTopic: 'जवाब विषय',
    generateEmail: 'ईमेल बनाएं', generateReply: 'जवाब बनाएं',
    generatingEmail: 'ईमेल बन रहा है...', generatingReply: 'जवाब बन रहा है...',
    generatedEmail: 'बना हुआ ईमेल', generatedReply: 'बना हुआ जवाब',
    topicRequiredMsg: 'कृपया पहले ईमेल विषय दर्ज करें।',
    noHistoryYet: 'अभी कोई इतिहास नहीं', noHistorySubtitle: 'निबंध, कविताएं या कहानियां बनाएं\nऔर वे यहां दिखेंगी।',
    startWriting: 'लिखना शुरू करें', clearAll: 'सब हटाएं',
    deleteHistory: 'इस आइटम को इतिहास से हटाएं?', deleteAllHistory: 'सारा इतिहास हटाएं?',
    delete: 'हटाएं', cancel: 'रद्द करें', all: 'सभी',
    settingsTitle: 'सेटिंग्स', account: 'खाता', subscription: 'सदस्यता',
    theme: 'थीम', languages: 'भाषाएं', reportContent: 'सामग्री रिपोर्ट करें',
    rateUs: 'हमें रेट करें', contactUs: 'संपर्क करें', about: 'के बारे में',
    privacyPolicy: 'गोपनीयता नीति', termsConditions: 'नियम और शर्तें',
    featureRequest: 'फीचर अनुरोध', logout: 'लॉग आउट', close: 'बंद करें',
    writingTone: 'लेखन शैली', length: 'लंबाई', generateParagraphs: 'पैराग्राफ बनाएं',
  },
  ur: {
    appName: 'AI رائٹر', askAnything: 'کچھ بھی پوچھیں…', selectTool: 'ٹول منتخب کریں',
    home: 'ہوم', history: 'تاریخ', settings: 'ترتیبات',
    essayWriter: 'مضمون نویس', essayDesc: 'اعلی معیار کے مضامین بنائیں۔',
    storyWriter: 'کہانی نویس', storyDesc: 'تخلیقی کہانیاں بنائیں۔',
    poemWriter: 'شاعر', poemDesc: 'الفاظ کو خوبصورت نظموں میں بدلیں۔',
    emailWriter: 'ای میل نویس', emailDesc: 'ذاتی ای میل لکھیں۔',
    paragraphWriter: 'پیراگراف نویس', paragraphDesc: 'کسی بھی موضوع پر واضح پیراگراف۔',
    enterTopic: 'موضوع درج کریں', topicPlaceholder: 'مثلاً شکرگزاری کی طاقت...',
    sampleText: 'نمونہ متن', essayType: 'مضمون کی قسم', academicLevel: 'تعلیمی سطح',
    generateEssay: 'مضمون بنائیں', generating: 'بن رہا ہے...', generatedEssay: 'بنا ہوا مضمون',
    short: 'چھوٹا', medium: 'درمیانہ', long: 'لمبا', pleaseEnterTopic: 'براہ کرم موضوع درج کریں',
    setCreativity: 'تخلیقیت منتخب کریں', selectGenre: 'صنف منتخب کریں', selectStyles: 'انداز منتخب کریں',
    generateStory: 'کہانی بنائیں', generatingStory: 'کہانی بن رہی ہے...', generatedStory: 'بنی ہوئی کہانی',
    topicRequired: 'موضوع ضروری ہے', enterTopicFirst: 'براہ کرم پہلے موضوع درج کریں۔',
    poemType: 'نظم کی قسم', generatePoem: 'نظم بنائیں', generatingPoem: 'نظم بن رہی ہے...', generatedPoem: 'بنی ہوئی نظم',
    writeEmail: 'ای میل لکھیں', replyEmail: 'ای میل کا جواب', emailTopic: 'ای میل موضوع', replyTopic: 'جواب موضوع',
    generateEmail: 'ای میل بنائیں', generateReply: 'جواب بنائیں',
    generatingEmail: 'ای میل بن رہا ہے...', generatingReply: 'جواب بن رہا ہے...',
    generatedEmail: 'بنا ہوا ای میل', generatedReply: 'بنا ہوا جواب',
    topicRequiredMsg: 'براہ کرم پہلے ای میل موضوع درج کریں۔',
    noHistoryYet: 'ابھی کوئی تاریخ نہیں', noHistorySubtitle: 'مضامین، نظمیں یا کہانیاں بنائیں\nاور وہ یہاں نظر آئیں گی۔',
    startWriting: 'لکھنا شروع کریں', clearAll: 'سب مٹائیں',
    deleteHistory: 'اس آئٹم کو تاریخ سے ہٹائیں؟', deleteAllHistory: 'تمام تاریخ مٹائیں؟',
    delete: 'مٹائیں', cancel: 'منسوخ', all: 'تمام',
    settingsTitle: 'ترتیبات', account: 'اکاؤنٹ', subscription: 'سبسکرپشن',
    theme: 'تھیم', languages: 'زبانیں', reportContent: 'مواد رپورٹ کریں',
    rateUs: 'ہمیں ریٹ کریں', contactUs: 'ہم سے رابطہ', about: 'بارے میں',
    privacyPolicy: 'رازداری کی پالیسی', termsConditions: 'شرائط و ضوابط',
    featureRequest: 'فیچر کی درخواست', logout: 'لاگ آؤٹ', close: 'بند کریں',
    writingTone: 'لکھنے کا انداز', length: 'طوالت', generateParagraphs: 'پیراگراف بنائیں',
  },
  ar: {
    appName: 'AI كاتب', askAnything: 'اسأل أي شيء…', selectTool: 'اختر الأداة',
    home: 'الرئيسية', history: 'السجل', settings: 'الإعدادات',
    essayWriter: 'كاتب المقالات', essayDesc: 'إنشاء مقالات عالية الجودة.',
    storyWriter: 'كاتب القصص', storyDesc: 'إنشاء قصص إبداعية.',
    poemWriter: 'كاتب الشعر', poemDesc: 'تحويل الكلمات إلى شعر جميل.',
    emailWriter: 'كاتب البريد', emailDesc: 'كتابة رسائل بريد إلكتروني.',
    paragraphWriter: 'كاتب الفقرات', paragraphDesc: 'فقرات واضحة لأي موضوع.',
    enterTopic: 'أدخل الموضوع', topicPlaceholder: 'مثل: قوة الامتنان...',
    sampleText: 'نص نموذجي', essayType: 'نوع المقالة', academicLevel: 'المستوى الأكاديمي',
    generateEssay: 'إنشاء مقالة', generating: 'جار الإنشاء...', generatedEssay: 'المقالة المُنشأة',
    short: 'قصير', medium: 'متوسط', long: 'طويل', pleaseEnterTopic: 'يرجى إدخال الموضوع',
    setCreativity: 'تعيين الإبداع', selectGenre: 'اختر النوع', selectStyles: 'اختر الأسلوب',
    generateStory: 'إنشاء قصة', generatingStory: 'جار إنشاء القصة...', generatedStory: 'القصة المُنشأة',
    topicRequired: 'الموضوع مطلوب', enterTopicFirst: 'يرجى إدخال الموضوع أولاً.',
    poemType: 'نوع القصيدة', generatePoem: 'إنشاء قصيدة', generatingPoem: 'جار إنشاء القصيدة...', generatedPoem: 'القصيدة المُنشأة',
    writeEmail: 'كتابة بريد', replyEmail: 'الرد على بريد', emailTopic: 'موضوع البريد', replyTopic: 'موضوع الرد',
    generateEmail: 'إنشاء بريد', generateReply: 'إنشاء رد',
    generatingEmail: 'جار إنشاء البريد...', generatingReply: 'جار إنشاء الرد...',
    generatedEmail: 'البريد المُنشأ', generatedReply: 'الرد المُنشأ',
    topicRequiredMsg: 'يرجى إدخال موضوع البريد أولاً.',
    noHistoryYet: 'لا يوجد سجل بعد', noHistorySubtitle: 'أنشئ مقالات أو قصائد أو قصصاً\nوستظهر هنا.',
    startWriting: 'ابدأ الكتابة', clearAll: 'مسح الكل',
    deleteHistory: 'إزالة هذا العنصر من السجل؟', deleteAllHistory: 'حذف كل السجل؟',
    delete: 'حذف', cancel: 'إلغاء', all: 'الكل',
    settingsTitle: 'الإعدادات', account: 'الحساب', subscription: 'الاشتراك',
    theme: 'المظهر', languages: 'اللغات', reportContent: 'الإبلاغ عن المحتوى',
    rateUs: 'قيّمنا', contactUs: 'اتصل بنا', about: 'حول التطبيق',
    privacyPolicy: 'سياسة الخصوصية', termsConditions: 'الشروط والأحكام',
    featureRequest: 'طلب ميزة', logout: 'تسجيل الخروج', close: 'إغلاق',
    writingTone: 'نبرة الكتابة', length: 'الطول', generateParagraphs: 'إنشاء فقرات',
  },
  fr: {
    appName: 'AI Écrivain', askAnything: "Posez n'importe quelle question…", selectTool: 'Sélectionner un outil',
    home: 'Accueil', history: 'Historique', settings: 'Paramètres',
    essayWriter: 'Rédacteur de dissertation', essayDesc: 'Générez des dissertations de qualité.',
    storyWriter: "Écrivain d'histoires", storyDesc: 'Créez des histoires imaginatives.',
    poemWriter: 'Poète', poemDesc: 'Transformez les mots en beaux poèmes.',
    emailWriter: "Rédacteur d'emails", emailDesc: 'Rédigez des emails personnalisés.',
    paragraphWriter: 'Rédacteur de paragraphes', paragraphDesc: 'Des paragraphes clairs sur tout sujet.',
    enterTopic: 'Entrez le sujet', topicPlaceholder: 'ex: La puissance de la gratitude...',
    sampleText: 'Texte exemple', essayType: 'Type de dissertation', academicLevel: 'Niveau académique',
    generateEssay: 'Générer la dissertation', generating: 'Génération...', generatedEssay: 'Dissertation générée',
    short: 'Court', medium: 'Moyen', long: 'Long', pleaseEnterTopic: 'Veuillez saisir un sujet',
    setCreativity: 'Définir la créativité', selectGenre: 'Sélectionner le genre', selectStyles: 'Sélectionner le style',
    generateStory: "Générer l'histoire", generatingStory: "Génération de l'histoire...", generatedStory: 'Histoire générée',
    topicRequired: 'Sujet requis', enterTopicFirst: "Veuillez d'abord saisir un sujet.",
    poemType: 'Type de poème', generatePoem: 'Générer le poème', generatingPoem: 'Génération du poème...', generatedPoem: 'Poème généré',
    writeEmail: 'Écrire un email', replyEmail: 'Répondre à un email', emailTopic: "Sujet de l'email", replyTopic: 'Sujet de la réponse',
    generateEmail: "Générer l'email", generateReply: 'Générer la réponse',
    generatingEmail: "Génération de l'email...", generatingReply: 'Génération de la réponse...',
    generatedEmail: 'Email généré', generatedReply: 'Réponse générée',
    topicRequiredMsg: "Veuillez d'abord saisir un sujet d'email.",
    noHistoryYet: "Pas encore d'historique", noHistorySubtitle: 'Générez des dissertations, poèmes ou histoires\net ils apparaîtront ici.',
    startWriting: 'Commencer à écrire', clearAll: 'Tout effacer',
    deleteHistory: "Supprimer cet élément de l'historique?", deleteAllHistory: "Supprimer tout l'historique?",
    delete: 'Supprimer', cancel: 'Annuler', all: 'Tout',
    settingsTitle: 'Paramètres', account: 'Compte', subscription: 'Abonnement',
    theme: 'Thème', languages: 'Langues', reportContent: 'Signaler du contenu',
    rateUs: 'Notez-nous', contactUs: 'Contactez-nous', about: 'À propos',
    privacyPolicy: 'Politique de confidentialité', termsConditions: 'Termes et conditions',
    featureRequest: 'Demande de fonctionnalité', logout: 'Se déconnecter', close: 'Fermer',
    writingTone: 'Ton de rédaction', length: 'Longueur', generateParagraphs: 'Générer des paragraphes',
  },
  es: {
    appName: 'AI Escritor', askAnything: 'Pregunta lo que quieras…', selectTool: 'Seleccionar herramienta',
    home: 'Inicio', history: 'Historial', settings: 'Configuración',
    essayWriter: 'Redactor de ensayos', essayDesc: 'Genera ensayos de alta calidad.',
    storyWriter: 'Escritor de historias', storyDesc: 'Crea historias imaginativas.',
    poemWriter: 'Escritor de poemas', poemDesc: 'Convierte palabras en bellos poemas.',
    emailWriter: 'Redactor de emails', emailDesc: 'Escribe emails personalizados.',
    paragraphWriter: 'Redactor de párrafos', paragraphDesc: 'Párrafos claros para cualquier tema.',
    enterTopic: 'Ingresa el tema', topicPlaceholder: 'ej: El poder de la gratitud...',
    sampleText: 'Texto de muestra', essayType: 'Tipo de ensayo', academicLevel: 'Nivel académico',
    generateEssay: 'Generar ensayo', generating: 'Generando...', generatedEssay: 'Ensayo generado',
    short: 'Corto', medium: 'Medio', long: 'Largo', pleaseEnterTopic: 'Por favor ingresa un tema',
    setCreativity: 'Establecer creatividad', selectGenre: 'Seleccionar género', selectStyles: 'Seleccionar estilos',
    generateStory: 'Generar historia', generatingStory: 'Generando historia...', generatedStory: 'Historia generada',
    topicRequired: 'Tema requerido', enterTopicFirst: 'Por favor ingresa un tema primero.',
    poemType: 'Tipo de poema', generatePoem: 'Generar poema', generatingPoem: 'Generando poema...', generatedPoem: 'Poema generado',
    writeEmail: 'Escribir email', replyEmail: 'Responder email', emailTopic: 'Tema del email', replyTopic: 'Tema de respuesta',
    generateEmail: 'Generar email', generateReply: 'Generar respuesta',
    generatingEmail: 'Generando email...', generatingReply: 'Generando respuesta...',
    generatedEmail: 'Email generado', generatedReply: 'Respuesta generada',
    topicRequiredMsg: 'Por favor ingresa un tema de email primero.',
    noHistoryYet: 'Aún sin historial', noHistorySubtitle: 'Genera ensayos, poemas o historias\ny aparecerán aquí.',
    startWriting: 'Comenzar a escribir', clearAll: 'Borrar todo',
    deleteHistory: '¿Eliminar este elemento?', deleteAllHistory: '¿Eliminar todo el historial?',
    delete: 'Eliminar', cancel: 'Cancelar', all: 'Todo',
    settingsTitle: 'Configuración', account: 'Cuenta', subscription: 'Suscripción',
    theme: 'Tema', languages: 'Idiomas', reportContent: 'Reportar contenido',
    rateUs: 'Calificanos', contactUs: 'Contáctanos', about: 'Acerca de',
    privacyPolicy: 'Política de privacidad', termsConditions: 'Términos y condiciones',
    featureRequest: 'Solicitud de función', logout: 'Cerrar sesión', close: 'Cerrar',
    writingTone: 'Tono de escritura', length: 'Longitud', generateParagraphs: 'Generar párrafos',
  },
  de: {
    appName: 'AI Schreiber', askAnything: 'Frag mich alles…', selectTool: 'Tool auswählen',
    home: 'Startseite', history: 'Verlauf', settings: 'Einstellungen',
    essayWriter: 'Aufsatz-Schreiber', essayDesc: 'Erstelle hochwertige Aufsätze.',
    storyWriter: 'Geschichten-Schreiber', storyDesc: 'Erstelle fantasievolle Geschichten.',
    poemWriter: 'Gedicht-Schreiber', poemDesc: 'Wörter in schöne Gedichte verwandeln.',
    emailWriter: 'E-Mail-Schreiber', emailDesc: 'Persönliche E-Mails schreiben.',
    paragraphWriter: 'Absatz-Schreiber', paragraphDesc: 'Klare Absätze für jedes Thema.',
    enterTopic: 'Thema eingeben', topicPlaceholder: 'z.B. Die Kraft der Dankbarkeit...',
    sampleText: 'Beispieltext', essayType: 'Aufsatztyp', academicLevel: 'Akademisches Niveau',
    generateEssay: 'Aufsatz erstellen', generating: 'Erstelle...', generatedEssay: 'Erstellter Aufsatz',
    short: 'Kurz', medium: 'Mittel', long: 'Lang', pleaseEnterTopic: 'Bitte Thema eingeben',
    setCreativity: 'Kreativität festlegen', selectGenre: 'Genre auswählen', selectStyles: 'Stil auswählen',
    generateStory: 'Geschichte erstellen', generatingStory: 'Geschichte wird erstellt...', generatedStory: 'Erstellte Geschichte',
    topicRequired: 'Thema erforderlich', enterTopicFirst: 'Bitte zuerst ein Thema eingeben.',
    poemType: 'Gedichttyp', generatePoem: 'Gedicht erstellen', generatingPoem: 'Gedicht wird erstellt...', generatedPoem: 'Erstelltes Gedicht',
    writeEmail: 'E-Mail schreiben', replyEmail: 'E-Mail beantworten', emailTopic: 'E-Mail-Thema', replyTopic: 'Antwortthema',
    generateEmail: 'E-Mail erstellen', generateReply: 'Antwort erstellen',
    generatingEmail: 'E-Mail wird erstellt...', generatingReply: 'Antwort wird erstellt...',
    generatedEmail: 'Erstellte E-Mail', generatedReply: 'Erstellte Antwort',
    topicRequiredMsg: 'Bitte zuerst ein E-Mail-Thema eingeben.',
    noHistoryYet: 'Noch kein Verlauf', noHistorySubtitle: 'Erstelle Aufsätze, Gedichte oder Geschichten\nund sie erscheinen hier.',
    startWriting: 'Schreiben beginnen', clearAll: 'Alles löschen',
    deleteHistory: 'Diesen Eintrag löschen?', deleteAllHistory: 'Gesamten Verlauf löschen?',
    delete: 'Löschen', cancel: 'Abbrechen', all: 'Alle',
    settingsTitle: 'Einstellungen', account: 'Konto', subscription: 'Abonnement',
    theme: 'Thema', languages: 'Sprachen', reportContent: 'Inhalt melden',
    rateUs: 'Bewerte uns', contactUs: 'Kontakt', about: 'Über uns',
    privacyPolicy: 'Datenschutzrichtlinie', termsConditions: 'AGB',
    featureRequest: 'Funktionsanfrage', logout: 'Abmelden', close: 'Schließen',
    writingTone: 'Schreibton', length: 'Länge', generateParagraphs: 'Absätze erstellen',
  },
  zh: {
    appName: 'AI 写作助手', askAnything: '随便问我什么…', selectTool: '选择工具',
    home: '首页', history: '历史', settings: '设置',
    essayWriter: '文章写作', essayDesc: '生成高质量文章。',
    storyWriter: '故事写作', storyDesc: '创作富有想象力的故事。',
    poemWriter: '诗歌写作', poemDesc: '将文字变成美丽的诗歌。',
    emailWriter: '邮件写作', emailDesc: '撰写个性化电子邮件。',
    paragraphWriter: '段落写作', paragraphDesc: '任何主题的清晰段落。',
    enterTopic: '输入主题', topicPlaceholder: '例如：感恩的力量...',
    sampleText: '示例文本', essayType: '文章类型', academicLevel: '学术水平',
    generateEssay: '生成文章', generating: '生成中...', generatedEssay: '生成的文章',
    short: '短', medium: '中', long: '长', pleaseEnterTopic: '请输入主题',
    setCreativity: '设置创意', selectGenre: '选择类型', selectStyles: '选择风格',
    generateStory: '生成故事', generatingStory: '生成故事中...', generatedStory: '生成的故事',
    topicRequired: '需要主题', enterTopicFirst: '请先输入主题。',
    poemType: '诗歌类型', generatePoem: '生成诗歌', generatingPoem: '生成诗歌中...', generatedPoem: '生成的诗歌',
    writeEmail: '写邮件', replyEmail: '回复邮件', emailTopic: '邮件主题', replyTopic: '回复主题',
    generateEmail: '生成邮件', generateReply: '生成回复',
    generatingEmail: '生成邮件中...', generatingReply: '生成回复中...',
    generatedEmail: '生成的邮件', generatedReply: '生成的回复',
    topicRequiredMsg: '请先输入邮件主题。',
    noHistoryYet: '暂无历史记录', noHistorySubtitle: '生成文章、诗歌或故事\n它们将显示在这里。',
    startWriting: '开始写作', clearAll: '清除所有',
    deleteHistory: '从历史中删除此项？', deleteAllHistory: '删除所有历史？',
    delete: '删除', cancel: '取消', all: '全部',
    settingsTitle: '设置', account: '账户', subscription: '订阅',
    theme: '主题', languages: '语言', reportContent: '举报内容',
    rateUs: '评分', contactUs: '联系我们', about: '关于',
    privacyPolicy: '隐私政策', termsConditions: '条款和条件',
    featureRequest: '功能请求', logout: '退出登录', close: '关闭',
    writingTone: '写作风格', length: '长度', generateParagraphs: '生成段落',
  },
  ja: {
    appName: 'AI ライター', askAnything: '何でも聞いてください…', selectTool: 'ツールを選択',
    home: 'ホーム', history: '履歴', settings: '設定',
    essayWriter: 'エッセイライター', essayDesc: '高品質なエッセイを生成。',
    storyWriter: 'ストーリーライター', storyDesc: '創造的なストーリーを作成。',
    poemWriter: '詩ライター', poemDesc: '言葉を美しい詩に変える。',
    emailWriter: 'メールライター', emailDesc: 'パーソナライズされたメールを作成。',
    paragraphWriter: '段落ライター', paragraphDesc: 'あらゆるトピックの明確な段落。',
    enterTopic: 'トピックを入力', topicPlaceholder: '例：感謝の力...',
    sampleText: 'サンプルテキスト', essayType: 'エッセイタイプ', academicLevel: '学術レベル',
    generateEssay: 'エッセイを生成', generating: '生成中...', generatedEssay: '生成されたエッセイ',
    short: '短い', medium: '中くらい', long: '長い', pleaseEnterTopic: 'トピックを入力してください',
    setCreativity: '創造性を設定', selectGenre: 'ジャンルを選択', selectStyles: 'スタイルを選択',
    generateStory: 'ストーリーを生成', generatingStory: 'ストーリーを生成中...', generatedStory: '生成されたストーリー',
    topicRequired: 'トピックが必要', enterTopicFirst: '最初にトピックを入力してください。',
    poemType: '詩のタイプ', generatePoem: '詩を生成', generatingPoem: '詩を生成中...', generatedPoem: '生成された詩',
    writeEmail: 'メールを書く', replyEmail: 'メールに返信', emailTopic: 'メールのトピック', replyTopic: '返信のトピック',
    generateEmail: 'メールを生成', generateReply: '返信を生成',
    generatingEmail: 'メールを生成中...', generatingReply: '返信を生成中...',
    generatedEmail: '生成されたメール', generatedReply: '生成された返信',
    topicRequiredMsg: 'まずメールのトピックを入力してください。',
    noHistoryYet: '履歴なし', noHistorySubtitle: 'エッセイ、詩、またはストーリーを生成すると\nここに表示されます。',
    startWriting: '書き始める', clearAll: 'すべて消去',
    deleteHistory: 'この項目を削除しますか？', deleteAllHistory: 'すべての履歴を削除しますか？',
    delete: '削除', cancel: 'キャンセル', all: 'すべて',
    settingsTitle: '設定', account: 'アカウント', subscription: 'サブスクリプション',
    theme: 'テーマ', languages: '言語', reportContent: 'コンテンツを報告',
    rateUs: '評価する', contactUs: 'お問い合わせ', about: 'アプリについて',
    privacyPolicy: 'プライバシーポリシー', termsConditions: '利用規約',
    featureRequest: '機能リクエスト', logout: 'ログアウト', close: '閉じる',
    writingTone: '文章のトーン', length: '長さ', generateParagraphs: '段落を生成',
  },
  ko: {
    appName: 'AI 작가', askAnything: '무엇이든 물어보세요…', selectTool: '도구 선택',
    home: '홈', history: '기록', settings: '설정',
    essayWriter: '에세이 작가', essayDesc: '고품질 에세이를 생성합니다.',
    storyWriter: '스토리 작가', storyDesc: '창의적인 이야기를 만듭니다.',
    poemWriter: '시 작가', poemDesc: '단어를 아름다운 시로 변환합니다.',
    emailWriter: '이메일 작가', emailDesc: '개인화된 이메일을 작성합니다.',
    paragraphWriter: '단락 작가', paragraphDesc: '모든 주제에 대한 명확한 단락.',
    enterTopic: '주제 입력', topicPlaceholder: '예: 감사의 힘...',
    sampleText: '샘플 텍스트', essayType: '에세이 유형', academicLevel: '학문 수준',
    generateEssay: '에세이 생성', generating: '생성 중...', generatedEssay: '생성된 에세이',
    short: '짧게', medium: '중간', long: '길게', pleaseEnterTopic: '주제를 입력하세요',
    setCreativity: '창의성 설정', selectGenre: '장르 선택', selectStyles: '스타일 선택',
    generateStory: '이야기 생성', generatingStory: '이야기 생성 중...', generatedStory: '생성된 이야기',
    topicRequired: '주제 필요', enterTopicFirst: '먼저 주제를 입력하세요.',
    poemType: '시 유형', generatePoem: '시 생성', generatingPoem: '시 생성 중...', generatedPoem: '생성된 시',
    writeEmail: '이메일 작성', replyEmail: '이메일 답장', emailTopic: '이메일 주제', replyTopic: '답장 주제',
    generateEmail: '이메일 생성', generateReply: '답장 생성',
    generatingEmail: '이메일 생성 중...', generatingReply: '답장 생성 중...',
    generatedEmail: '생성된 이메일', generatedReply: '생성된 답장',
    topicRequiredMsg: '먼저 이메일 주제를 입력하세요.',
    noHistoryYet: '아직 기록 없음', noHistorySubtitle: '에세이, 시 또는 이야기를 생성하면\n여기에 표시됩니다.',
    startWriting: '작성 시작', clearAll: '모두 지우기',
    deleteHistory: '이 항목을 삭제하시겠습니까?', deleteAllHistory: '모든 기록을 삭제하시겠습니까?',
    delete: '삭제', cancel: '취소', all: '전체',
    settingsTitle: '설정', account: '계정', subscription: '구독',
    theme: '테마', languages: '언어', reportContent: '콘텐츠 신고',
    rateUs: '평가하기', contactUs: '문의하기', about: '앱 정보',
    privacyPolicy: '개인정보 처리방침', termsConditions: '이용약관',
    featureRequest: '기능 요청', logout: '로그아웃', close: '닫기',
    writingTone: '글쓰기 톤', length: '길이', generateParagraphs: '단락 생성',
  },
  pt: {
    appName: 'AI Escritor', askAnything: 'Pergunte qualquer coisa…', selectTool: 'Selecionar ferramenta',
    home: 'Início', history: 'Histórico', settings: 'Configurações',
    essayWriter: 'Redator de redações', essayDesc: 'Gere redações de alta qualidade.',
    storyWriter: 'Escritor de histórias', storyDesc: 'Crie histórias imaginativas.',
    poemWriter: 'Escritor de poemas', poemDesc: 'Transforme palavras em belos poemas.',
    emailWriter: 'Redator de e-mails', emailDesc: 'Escreva e-mails personalizados.',
    paragraphWriter: 'Redator de parágrafos', paragraphDesc: 'Parágrafos claros para qualquer tema.',
    enterTopic: 'Insira o tema', topicPlaceholder: 'ex: O poder da gratidão...',
    sampleText: 'Texto de exemplo', essayType: 'Tipo de redação', academicLevel: 'Nível acadêmico',
    generateEssay: 'Gerar redação', generating: 'Gerando...', generatedEssay: 'Redação gerada',
    short: 'Curto', medium: 'Médio', long: 'Longo', pleaseEnterTopic: 'Por favor insira um tema',
    setCreativity: 'Definir criatividade', selectGenre: 'Selecionar gênero', selectStyles: 'Selecionar estilos',
    generateStory: 'Gerar história', generatingStory: 'Gerando história...', generatedStory: 'História gerada',
    topicRequired: 'Tema necessário', enterTopicFirst: 'Por favor insira um tema primeiro.',
    poemType: 'Tipo de poema', generatePoem: 'Gerar poema', generatingPoem: 'Gerando poema...', generatedPoem: 'Poema gerado',
    writeEmail: 'Escrever e-mail', replyEmail: 'Responder e-mail', emailTopic: 'Tema do e-mail', replyTopic: 'Tema da resposta',
    generateEmail: 'Gerar e-mail', generateReply: 'Gerar resposta',
    generatingEmail: 'Gerando e-mail...', generatingReply: 'Gerando resposta...',
    generatedEmail: 'E-mail gerado', generatedReply: 'Resposta gerada',
    topicRequiredMsg: 'Por favor insira um tema de e-mail primeiro.',
    noHistoryYet: 'Sem histórico ainda', noHistorySubtitle: 'Gere redações, poemas ou histórias\ne elas aparecerão aqui.',
    startWriting: 'Começar a escrever', clearAll: 'Limpar tudo',
    deleteHistory: 'Remover este item do histórico?', deleteAllHistory: 'Excluir todo o histórico?',
    delete: 'Excluir', cancel: 'Cancelar', all: 'Todos',
    settingsTitle: 'Configurações', account: 'Conta', subscription: 'Assinatura',
    theme: 'Tema', languages: 'Idiomas', reportContent: 'Reportar conteúdo',
    rateUs: 'Avalie-nos', contactUs: 'Contate-nos', about: 'Sobre',
    privacyPolicy: 'Política de privacidade', termsConditions: 'Termos e condições',
    featureRequest: 'Solicitação de recurso', logout: 'Sair', close: 'Fechar',
    writingTone: 'Tom de escrita', length: 'Comprimento', generateParagraphs: 'Gerar parágrafos',
  },
  ru: {
    appName: 'AI Писатель', askAnything: 'Спросите что угодно…', selectTool: 'Выбрать инструмент',
    home: 'Главная', history: 'История', settings: 'Настройки',
    essayWriter: 'Писатель эссе', essayDesc: 'Генерируйте качественные эссе.',
    storyWriter: 'Писатель рассказов', storyDesc: 'Создавайте воображаемые истории.',
    poemWriter: 'Поэт', poemDesc: 'Превращайте слова в красивые стихи.',
    emailWriter: 'Писатель писем', emailDesc: 'Пишите персонализированные письма.',
    paragraphWriter: 'Писатель абзацев', paragraphDesc: 'Чёткие абзацы на любую тему.',
    enterTopic: 'Введите тему', topicPlaceholder: 'например: Сила благодарности...',
    sampleText: 'Пример текста', essayType: 'Тип эссе', academicLevel: 'Академический уровень',
    generateEssay: 'Создать эссе', generating: 'Создание...', generatedEssay: 'Созданное эссе',
    short: 'Короткий', medium: 'Средний', long: 'Длинный', pleaseEnterTopic: 'Пожалуйста, введите тему',
    setCreativity: 'Установить творчество', selectGenre: 'Выбрать жанр', selectStyles: 'Выбрать стиль',
    generateStory: 'Создать историю', generatingStory: 'Создание истории...', generatedStory: 'Созданная история',
    topicRequired: 'Тема обязательна', enterTopicFirst: 'Пожалуйста, сначала введите тему.',
    poemType: 'Тип стихотворения', generatePoem: 'Создать стихотворение', generatingPoem: 'Создание стихотворения...', generatedPoem: 'Созданное стихотворение',
    writeEmail: 'Написать письмо', replyEmail: 'Ответить на письмо', emailTopic: 'Тема письма', replyTopic: 'Тема ответа',
    generateEmail: 'Создать письмо', generateReply: 'Создать ответ',
    generatingEmail: 'Создание письма...', generatingReply: 'Создание ответа...',
    generatedEmail: 'Созданное письмо', generatedReply: 'Созданный ответ',
    topicRequiredMsg: 'Пожалуйста, сначала введите тему письма.',
    noHistoryYet: 'Истории пока нет', noHistorySubtitle: 'Создайте эссе, стихи или истории\nи они появятся здесь.',
    startWriting: 'Начать писать', clearAll: 'Очистить всё',
    deleteHistory: 'Удалить этот элемент из истории?', deleteAllHistory: 'Удалить всю историю?',
    delete: 'Удалить', cancel: 'Отмена', all: 'Все',
    settingsTitle: 'Настройки', account: 'Аккаунт', subscription: 'Подписка',
    theme: 'Тема', languages: 'Языки', reportContent: 'Пожаловаться на контент',
    rateUs: 'Оценить нас', contactUs: 'Связаться с нами', about: 'О приложении',
    privacyPolicy: 'Политика конфиденциальности', termsConditions: 'Условия использования',
    featureRequest: 'Запрос функции', logout: 'Выйти', close: 'Закрыть',
    writingTone: 'Тон написания', length: 'Длина', generateParagraphs: 'Создать абзацы',
  },
  it: {
    appName: 'AI Scrittore', askAnything: 'Chiedimi qualsiasi cosa…', selectTool: 'Seleziona strumento',
    home: 'Home', history: 'Cronologia', settings: 'Impostazioni',
    essayWriter: 'Scrittore di saggi', essayDesc: 'Genera saggi di alta qualità.',
    storyWriter: 'Scrittore di storie', storyDesc: 'Crea storie immaginative.',
    poemWriter: 'Scrittore di poesie', poemDesc: 'Trasforma le parole in belle poesie.',
    emailWriter: 'Scrittore di email', emailDesc: 'Scrivi email personalizzate.',
    paragraphWriter: 'Scrittore di paragrafi', paragraphDesc: 'Paragrafi chiari per qualsiasi argomento.',
    enterTopic: "Inserisci l'argomento", topicPlaceholder: 'es: Il potere della gratitudine...',
    sampleText: 'Testo di esempio', essayType: 'Tipo di saggio', academicLevel: 'Livello accademico',
    generateEssay: 'Genera saggio', generating: 'Generando...', generatedEssay: 'Saggio generato',
    short: 'Corto', medium: 'Medio', long: 'Lungo', pleaseEnterTopic: "Inserisci un argomento",
    setCreativity: 'Imposta creatività', selectGenre: 'Seleziona genere', selectStyles: 'Seleziona stili',
    generateStory: 'Genera storia', generatingStory: 'Generando storia...', generatedStory: 'Storia generata',
    topicRequired: 'Argomento richiesto', enterTopicFirst: "Inserisci prima un argomento.",
    poemType: 'Tipo di poesia', generatePoem: 'Genera poesia', generatingPoem: 'Generando poesia...', generatedPoem: 'Poesia generata',
    writeEmail: 'Scrivi email', replyEmail: "Rispondi all'email", emailTopic: "Argomento email", replyTopic: 'Argomento risposta',
    generateEmail: 'Genera email', generateReply: 'Genera risposta',
    generatingEmail: 'Generando email...', generatingReply: 'Generando risposta...',
    generatedEmail: 'Email generata', generatedReply: 'Risposta generata',
    topicRequiredMsg: "Inserisci prima un argomento email.",
    noHistoryYet: 'Nessuna cronologia', noHistorySubtitle: 'Genera saggi, poesie o storie\ne appariranno qui.',
    startWriting: 'Inizia a scrivere', clearAll: 'Cancella tutto',
    deleteHistory: 'Rimuovere questo elemento?', deleteAllHistory: 'Eliminare tutta la cronologia?',
    delete: 'Elimina', cancel: 'Annulla', all: 'Tutti',
    settingsTitle: 'Impostazioni', account: 'Account', subscription: 'Abbonamento',
    theme: 'Tema', languages: 'Lingue', reportContent: 'Segnala contenuto',
    rateUs: 'Valutaci', contactUs: 'Contattaci', about: "Informazioni sull'app",
    privacyPolicy: 'Informativa sulla privacy', termsConditions: 'Termini e condizioni',
    featureRequest: 'Richiesta funzione', logout: 'Esci', close: 'Chiudi',
    writingTone: 'Tono di scrittura', length: 'Lunghezza', generateParagraphs: 'Genera paragrafi',
  },
  tr: {
    appName: 'AI Yazar', askAnything: 'Her şeyi sorabilirsiniz…', selectTool: 'Araç seç',
    home: 'Ana Sayfa', history: 'Geçmiş', settings: 'Ayarlar',
    essayWriter: 'Makale Yazarı', essayDesc: 'Yüksek kaliteli makaleler oluşturun.',
    storyWriter: 'Hikaye Yazarı', storyDesc: 'Yaratıcı hikayeler oluşturun.',
    poemWriter: 'Şair', poemDesc: 'Kelimeleri güzel şiirlere dönüştürün.',
    emailWriter: 'E-posta Yazarı', emailDesc: 'Kişiselleştirilmiş e-postalar yazın.',
    paragraphWriter: 'Paragraf Yazarı', paragraphDesc: 'Her konu için açık paragraflar.',
    enterTopic: 'Konu girin', topicPlaceholder: 'örn: Minnettarlığın gücü...',
    sampleText: 'Örnek metin', essayType: 'Makale türü', academicLevel: 'Akademik seviye',
    generateEssay: 'Makale oluştur', generating: 'Oluşturuluyor...', generatedEssay: 'Oluşturulan makale',
    short: 'Kısa', medium: 'Orta', long: 'Uzun', pleaseEnterTopic: 'Lütfen konu girin',
    setCreativity: 'Yaratıcılığı ayarla', selectGenre: 'Tür seç', selectStyles: 'Stil seç',
    generateStory: 'Hikaye oluştur', generatingStory: 'Hikaye oluşturuluyor...', generatedStory: 'Oluşturulan hikaye',
    topicRequired: 'Konu gerekli', enterTopicFirst: 'Lütfen önce konu girin.',
    poemType: 'Şiir türü', generatePoem: 'Şiir oluştur', generatingPoem: 'Şiir oluşturuluyor...', generatedPoem: 'Oluşturulan şiir',
    writeEmail: 'E-posta yaz', replyEmail: 'E-postaya yanıtla', emailTopic: 'E-posta konusu', replyTopic: 'Yanıt konusu',
    generateEmail: 'E-posta oluştur', generateReply: 'Yanıt oluştur',
    generatingEmail: 'E-posta oluşturuluyor...', generatingReply: 'Yanıt oluşturuluyor...',
    generatedEmail: 'Oluşturulan e-posta', generatedReply: 'Oluşturulan yanıt',
    topicRequiredMsg: 'Lütfen önce e-posta konusu girin.',
    noHistoryYet: 'Henüz geçmiş yok', noHistorySubtitle: 'Makaleler, şiirler veya hikayeler oluşturun\nve burada görünecekler.',
    startWriting: 'Yazmaya başla', clearAll: 'Tümünü temizle',
    deleteHistory: 'Bu öğeyi geçmişten kaldır?', deleteAllHistory: 'Tüm geçmişi sil?',
    delete: 'Sil', cancel: 'İptal', all: 'Tümü',
    settingsTitle: 'Ayarlar', account: 'Hesap', subscription: 'Abonelik',
    theme: 'Tema', languages: 'Diller', reportContent: 'İçerik bildir',
    rateUs: 'Bizi değerlendirin', contactUs: 'Bize ulaşın', about: 'Hakkında',
    privacyPolicy: 'Gizlilik politikası', termsConditions: 'Şartlar ve koşullar',
    featureRequest: 'Özellik isteği', logout: 'Çıkış yap', close: 'Kapat',
    writingTone: 'Yazı tonu', length: 'Uzunluk', generateParagraphs: 'Paragraf oluştur',
  },
  bn: {
    appName: 'AI লেখক', askAnything: 'যেকোনো কিছু জিজ্ঞেস করুন…', selectTool: 'টুল বেছে নিন',
    home: 'হোম', history: 'ইতিহাস', settings: 'সেটিংস',
    essayWriter: 'প্রবন্ধ লেখক', essayDesc: 'উচ্চ মানের প্রবন্ধ তৈরি করুন।',
    storyWriter: 'গল্প লেখক', storyDesc: 'কল্পনাপ্রবণ গল্প তৈরি করুন।',
    poemWriter: 'কবিতা লেখক', poemDesc: 'শব্দকে সুন্দর কবিতায় রূপান্তর করুন।',
    emailWriter: 'ইমেইল লেখক', emailDesc: 'ব্যক্তিগত ইমেইল লিখুন।',
    paragraphWriter: 'অনুচ্ছেদ লেখক', paragraphDesc: 'যেকোনো বিষয়ে স্পষ্ট অনুচ্ছেদ।',
    enterTopic: 'বিষয় লিখুন', topicPlaceholder: 'যেমন কৃতজ্ঞতার শক্তি...',
    sampleText: 'নমুনা পাঠ্য', essayType: 'প্রবন্ধের ধরন', academicLevel: 'শিক্ষাগত স্তর',
    generateEssay: 'প্রবন্ধ তৈরি করুন', generating: 'তৈরি হচ্ছে...', generatedEssay: 'তৈরি করা প্রবন্ধ',
    short: 'ছোট', medium: 'মাঝারি', long: 'দীর্ঘ', pleaseEnterTopic: 'অনুগ্রহ করে বিষয় লিখুন',
    setCreativity: 'সৃজনশীলতা সেট করুন', selectGenre: 'ঘরানা বেছে নিন', selectStyles: 'শৈলী বেছে নিন',
    generateStory: 'গল্প তৈরি করুন', generatingStory: 'গল্প তৈরি হচ্ছে...', generatedStory: 'তৈরি করা গল্প',
    topicRequired: 'বিষয় প্রয়োজন', enterTopicFirst: 'অনুগ্রহ করে প্রথমে বিষয় লিখুন।',
    poemType: 'কবিতার ধরন', generatePoem: 'কবিতা তৈরি করুন', generatingPoem: 'কবিতা তৈরি হচ্ছে...', generatedPoem: 'তৈরি করা কবিতা',
    writeEmail: 'ইমেইল লিখুন', replyEmail: 'ইমেইলের উত্তর দিন', emailTopic: 'ইমেইল বিষয়', replyTopic: 'উত্তরের বিষয়',
    generateEmail: 'ইমেইল তৈরি করুন', generateReply: 'উত্তর তৈরি করুন',
    generatingEmail: 'ইমেইল তৈরি হচ্ছে...', generatingReply: 'উত্তর তৈরি হচ্ছে...',
    generatedEmail: 'তৈরি করা ইমেইল', generatedReply: 'তৈরি করা উত্তর',
    topicRequiredMsg: 'অনুগ্রহ করে প্রথমে ইমেইলের বিষয় লিখুন।',
    noHistoryYet: 'এখনো কোনো ইতিহাস নেই', noHistorySubtitle: 'প্রবন্ধ, কবিতা বা গল্প তৈরি করুন\nএবং সেগুলি এখানে দেখা যাবে।',
    startWriting: 'লেখা শুরু করুন', clearAll: 'সব মুছুন',
    deleteHistory: 'এই আইটেমটি মুছবেন?', deleteAllHistory: 'সমস্ত ইতিহাস মুছবেন?',
    delete: 'মুছুন', cancel: 'বাতিল', all: 'সব',
    settingsTitle: 'সেটিংস', account: 'অ্যাকাউন্ট', subscription: 'সাবস্ক্রিপশন',
    theme: 'থিম', languages: 'ভাষা', reportContent: 'বিষয়বস্তু রিপোর্ট করুন',
    rateUs: 'আমাদের রেট করুন', contactUs: 'যোগাযোগ করুন', about: 'সম্পর্কে',
    privacyPolicy: 'গোপনীয়তা নীতি', termsConditions: 'শর্ত ও নিয়ম',
    featureRequest: 'বৈশিষ্ট্য অনুরোধ', logout: 'লগ আউট', close: 'বন্ধ করুন',
    writingTone: 'লেখার স্বর', length: 'দৈর্ঘ্য', generateParagraphs: 'অনুচ্ছেদ তৈরি করুন',
  },
  id: {
    appName: 'AI Penulis', askAnything: 'Tanyakan apa saja…', selectTool: 'Pilih alat',
    home: 'Beranda', history: 'Riwayat', settings: 'Pengaturan',
    essayWriter: 'Penulis Esai', essayDesc: 'Buat esai berkualitas tinggi.',
    storyWriter: 'Penulis Cerita', storyDesc: 'Buat cerita yang imajinatif.',
    poemWriter: 'Penulis Puisi', poemDesc: 'Ubah kata-kata menjadi puisi indah.',
    emailWriter: 'Penulis Email', emailDesc: 'Tulis email yang dipersonalisasi.',
    paragraphWriter: 'Penulis Paragraf', paragraphDesc: 'Paragraf jelas untuk topik apa pun.',
    enterTopic: 'Masukkan topik', topicPlaceholder: 'mis: Kekuatan rasa syukur...',
    sampleText: 'Teks contoh', essayType: 'Jenis esai', academicLevel: 'Tingkat akademik',
    generateEssay: 'Buat esai', generating: 'Membuat...', generatedEssay: 'Esai yang dibuat',
    short: 'Pendek', medium: 'Sedang', long: 'Panjang', pleaseEnterTopic: 'Harap masukkan topik',
    setCreativity: 'Atur kreativitas', selectGenre: 'Pilih genre', selectStyles: 'Pilih gaya',
    generateStory: 'Buat cerita', generatingStory: 'Membuat cerita...', generatedStory: 'Cerita yang dibuat',
    topicRequired: 'Topik diperlukan', enterTopicFirst: 'Harap masukkan topik terlebih dahulu.',
    poemType: 'Jenis puisi', generatePoem: 'Buat puisi', generatingPoem: 'Membuat puisi...', generatedPoem: 'Puisi yang dibuat',
    writeEmail: 'Tulis email', replyEmail: 'Balas email', emailTopic: 'Topik email', replyTopic: 'Topik balasan',
    generateEmail: 'Buat email', generateReply: 'Buat balasan',
    generatingEmail: 'Membuat email...', generatingReply: 'Membuat balasan...',
    generatedEmail: 'Email yang dibuat', generatedReply: 'Balasan yang dibuat',
    topicRequiredMsg: 'Harap masukkan topik email terlebih dahulu.',
    noHistoryYet: 'Belum ada riwayat', noHistorySubtitle: 'Buat esai, puisi, atau cerita\ndan akan muncul di sini.',
    startWriting: 'Mulai menulis', clearAll: 'Hapus semua',
    deleteHistory: 'Hapus item ini dari riwayat?', deleteAllHistory: 'Hapus semua riwayat?',
    delete: 'Hapus', cancel: 'Batal', all: 'Semua',
    settingsTitle: 'Pengaturan', account: 'Akun', subscription: 'Langganan',
    theme: 'Tema', languages: 'Bahasa', reportContent: 'Laporkan konten',
    rateUs: 'Beri nilai', contactUs: 'Hubungi kami', about: 'Tentang',
    privacyPolicy: 'Kebijakan privasi', termsConditions: 'Syarat dan ketentuan',
    featureRequest: 'Permintaan fitur', logout: 'Keluar', close: 'Tutup',
    writingTone: 'Nada tulisan', length: 'Panjang', generateParagraphs: 'Buat paragraf',
  },
};

export function ThemeProvider({ children }) {
  const [mode, setMode]         = useState('dark');
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const load = async () => {
      try {
        const savedTheme = await AsyncStorage.getItem('app_theme');
        const savedLang  = await AsyncStorage.getItem('app_language');
        if (savedTheme === 'light' || savedTheme === 'dark') setMode(savedTheme);
        if (savedLang && TRANSLATIONS[savedLang]) setLanguage(savedLang);
      } catch (e) {
        console.log('Theme load error:', e);
      }
    };
    load();
  }, []);

  const toggleTheme = async (newMode) => {
    setMode(newMode);
    await AsyncStorage.setItem('app_theme', newMode);
  };

  const changeLanguage = async (lang) => {
    setLanguage(lang);
    await AsyncStorage.setItem('app_language', lang);
  };

  // ✅ t() — kisi bhi screen mein use karo
  const t = (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;

  return (
    <ThemeContext.Provider value={{
      mode,
      theme: THEMES[mode],
      toggleTheme,
      language,
      changeLanguage,
      t,
    }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  return useContext(ThemeContext);
}